backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "Categories"
        name: "tags"
        multiple: true
        create: true
        options: ["Techniques", "Tips", "Stitch patterns", "Ebook"]
  - label: "Sidebar"
    name: "sidebar"
    editor:
      preview: false
    files:
      - label: "About me"
        name: "about_me"
        file: "src/_data/about_me.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Image, name: image, widget: image }
      - label: "Banner"
        name: "sidebar_banner"
        file: "src/_data/sidebar_banner.yaml"
        fields:
          - { label: Image, name: image, widget: image }
          - { label: URL, name: url, widget: string }
          - { label: Fallback text, name: alt, widget: string }
      - label: "Recent patterns"
        name: "recent_patterns"
        file: "src/_data/recent_patterns.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Patterns
            name: patterns
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: URL, name: url, widget: string }
              - { label: Fallback text, name: alt, widget: string }

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Facebook URL, name: facebook_url, widget: string }
          - { label: Instagram URL, name: instagram_url, widget: string }
          - { label: Ravelry URL, name: ravelry_url, widget: string }
